services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:@mysql:3306/nestapp

    ports:
      - 3007:3000


  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: nestapp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3308:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""  


volumes:
  mysql_data:
